---
title: "lecture_4.3"
author: "Gian Zlupko"
date: "2023-04-03"
output: html_document
---



```{r}
USArrests

arrest <- USArrests
# view row names and column names
rownames(USArrests) 
row.names(USArrests) # alternative
colnames(USArrests) 
names(USArrests) # alternative 
```


Summarizing the data
```{r}
str(USArrests) 
summary(USArrests) 
dim(USArrests) 
```




```{r}

for (i in 1:4){ 
  print(mean(arrest[, i]))
}

# alternatively `sapply()`
sapply(arrest, mean)


```


PCA 
```{r}
pca_arrests <- prcomp(arrest, center = T, scale = T) 
names(pca_arrests) # examine model attributes that can be extracted 

pca_arrests$center # means of the original variables 

summary(pca_arrests) 


# scree plot
plot(pca_arrests, type = "l",
     main = "Scree Plot") 

# biplot for principal components space 
biplot(pca_arrests, scale = 0)
```


```{r}
pca.var <- pca_arrests$sdev^2
plot(pca.var, type = "b")
axis(1, at = c(1,2,3,4), c("1", "2", "3", "4")) 

cumsum(pca.var) 
```



Cumulative sum 
```{r}
x = c(1,2,-3,8)
cumsum(x) 
```



K-means 
```{r}
# randomly generate data 
x = matrix(rnorm(50*2), ncol = 2) 
head(x)

# k-means

km1 = kmeans(x, centers = 2)
km1$cluster

plot(x, col = km1$cluster, 
     main = "k-means with k = 2", 
     xlab = "X1", 
     ylab = "X2", pch = 19, cex = 1) 

```




```{r}
km2 = kmeans(x, centers = 3, nstart = 20)
km2

plot(x, col = km2$cluster, 
     pch = 20) 
```





K-means cluster analysis

```{r}
x = matrix(rnorm(50*2), ncol = 2) 

kmeans(x, 2, nstart = 20) 
```





HCA
First we will use complete linkage (group method) and using euclidean as the distance metric. The grouping method determines how groups should be merged. 

```{r}
dist_mat = dist(x) 

hc.complete = hclust(d = dist_mat, method = "complete")
hc.average = hclust(dist_mat, method = "average")
hc.single = hclust(dist_mat, method = "single")

# plot the graphs
par(mfrow = c(1,3)) # mfrow() tells R how to structure the window 
plot(hc.complete, main =  'Complete Linkage', xlab = "", 
     sub = "", cex = .9)
plot(hc.average, main = "Average Linkage", xlab = "", sub  = "", cex =0.9)
plot(hc.single, main = "Single Linkage", xlab = "", sub  = "", cex =0.9)
```






```{r}

```




